name: Test and Build
on:
  push:
    tags:
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Tests
        run: lein test
      - name: Build
        run: lein jar
  publish:
    name: 'Publish to Clojars'
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: lein deploy publish
        env:
          CLOJARS_USERNAME: w-se
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
      
    
